### ISSUE TITLE
线上地址页面打开会报错

### ISSUE THREAD

**Issue by anyone-yuren** [baimingxuan/react-admin-design#3]
![image](https://github.com/baimingxuan/react-admin-design/assets/14817820/b93e0f20-aa9a-47a2-aaf9-2824850cf23b)

**Comment by baimingxuan** [comment]
路由懒加载出现莫名bug，现已修复

**Comment by anyone-yuren** [comment]
这是新版本router引起的，你这样写就失去了懒加载机制了

**Comment by anyone-yuren** [comment]
已解决，详见：https://github.com/baimingxuan/react-admin-design/pull/4
